[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
dictionary = "RdnxCRhkc1E6o2rL7agP5dmDLe1JkZenV5YehvedkeR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/hernah/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
